### PR TITLE
docs(CLI) updates

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Documentation

## Other information

Mainly adds new `compilerOptions`.

Also addresses #731 (well, not FirstSteps, but in the CLI.  We can go back and do FirstSteps once this one is approved)

Also cleans up a few leftovers from first version.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
I'm not entirely sure if we should use **warning** quote for that:

image

It looks quite scary (like a deprecation warning 😄). Maybe we can just turn it into a normal paragraph?

**Comment by johnbiundo** [comment]
Yeah, it looks a lot scarier rendered than it did in MD preview 😄 

@kamilmysliwiec Do you have any other changes?  I could re-submit changing it to an INFO note, but seems like you might prefer plain text?  If so, and you have no other comments, do you want to decide which way to go and merge it?

I'm OK either way, but my rationale for **some** call-out format is that it is really more of a "read this one time/side note" to the docs, so trying not to disrupt the main flow when someone is returning to this page for reference, as opposed to reading it for the first time.

**Comment by kamilmysliwiec** [comment]
> @kamilmysliwiec Do you have any other changes? I could re-submit changing it to an INFO note, but seems like you might prefer plain text?

I think the plain text would be enough honestly. :)

Everything else looks great!

**Comment by johnbiundo** [comment]
OK, changes made.  Sorry for the ugly commit history.  I had some local git corruption and had to reclone, and, well... that's what it is.  If you want me to clean that up, let me know.

**Comment by johnbiundo** [comment]
Fixed!

**Pull request merged**
