### PR TITLE
docs(interceptors):  Update interceptors.md, extend timeout interceptor

### PR DESCRIPTION
**Pull request by KMNowak**
Add customizable logic to timeout interceptor.
 Now, just before timeout is thrown, additional actions (like releasing resources) can be taken.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Other... Please describe: Documentation
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Extend sample timeout interceptor. Now can easily add additional logic before throwing `ReqestTimeoutException`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
What about this instead:
```typescript
return next.handle().pipe(
    timeout(3000),
    catchError((err) => {
       if (check timeout err here) { 
         return throwError(new RequestTimeoutException());
       }
       return throwError(err);
   }),
);
```
You don't need promises to perform additional actions

**Comment by KMNowak** [comment]
Yes, your solution is much more straightforward.
To be precise, what about:

```typescript
import { Injectable, NestInterceptor, ExecutionContext, CallHandler, RequestTimeoutException } from '@nestjs/common';
import { Observable, throwError, TimeoutError } from 'rxjs';
import { catchError, timeout } from 'rxjs/operators';

@Injectable()
export class TimeoutInterceptor implements NestInterceptor {
    intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
        return next.handle().pipe(
            timeout(80),
            catchError(err => {
                if (err instanceof TimeoutError) {
                    return throwError(new RequestTimeoutException())
                }

                return throwError(err)
            })
        );
    };
};
```

**Comment by kamilmysliwiec** [comment]
Looks great!

**Comment by KMNowak** [comment]
If you like the idea of throwing correct 408 (instead of default 500) and adding custom operations before, please merge.

**Pull request merged**
