### PR TITLE
docs(guards, interceptors, pipes): wording fix

### PR DESCRIPTION
**Pull request by kugaudo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: (https://github.com/nestjs/docs.nestjs.com/issues/2202)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jmcdo29 — APPROVED** [review]
LGTM

**Review by Tony133 — APPROVED** [review]

**Review by micalevisk — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
I think that was the original form and then John rephrased that to what we have in the docs now. I'm not a native speaker so I'm not sure which sentence sounds/looks better. I personally prefer the current version cc @MarkPieszak

**Comment by kugaudo** [comment]
@kamilmysliwiec the current version is totally ambiguous. I'm new to Nest. When I read this statement, I thought that a pipe is any class annotated with @Injectable. The dot. You put it for some reason, so I'm making a stop, start scrolling down, etc.

**Comment by kamilmysliwiec** [comment]
Fair enough @kugaudo!

**Pull request merged**
