### PR TITLE
docs (logger): add missing Injectable decorator to custom logger service class

### PR DESCRIPTION
**Pull request by sebastiendan**
## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jmcdo29 — COMMENTED** [review]
_Technically_ this isn't needed. There's nothing that is injected into the `Logger` class, so the `@Injectable()` here is extraneous. We can still add it for continuity, but it isn't explicitly necessary

**Comment by sebastiendan** [comment]
> _Technically_ this isn't needed. There's nothing that is injected into the `Logger` class, so the `@Injectable()` here is extraneous. We can still add it for continuity, but it isn't explicitly necessary

I see. In that case another proposed change could be adding a mention to the need for the decorator in the later `Dependency injection` section where `ConfigService` is referred as an example (but perhaps it is expected that the reader knows any dependency injected in the class constructor requires the `Injectable` class decorator?).

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/2907#pullrequestreview-1742799827

**Comment by kamilmysliwiec** [comment]
I figured let's just add it for simplicity sake

**Pull request merged**
