### PR TITLE
docs(lifecycle-events) update

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Documentation

## Other information

@kamilmysliwiec, @BrunnerLivio  Lifecycle events chapter proposed edits, for your review.

### CODE REVIEW

**Comment by johnbiundo** [comment]
There might be a couple of nits. I realized I say `When lifecycle hooks are enabled, `, but I think it's only required to enable shutdown.  Also, I reference microservices, websockets -- we don't usually do that in these sections of the docs, so I wonder if I should refer only to the HTTPServer for connection management?

**Comment by johnbiundo** [comment]
closes #624

**Comment by kamilmysliwiec** [comment]
> I realized I say When lifecycle hooks are enabled, , but I think it's only required to enable shutdown. 

Exactly. It's required only for shutdown

**Comment by kamilmysliwiec** [comment]
I'll try to adjust the diagram image to the docs font + color pallete shortly 💪

**Pull request merged**
