### PR TITLE
docs(filters): fix passing error parameter

### PR DESCRIPTION
**Pull request by olivewind**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

image

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
HttpAdapterHost != ArgumentsHost

**Comment by olivewind** [comment]
@kamilmysliwiec I know, but according to the code provided by the documentation, an error will be thrown

**Comment by jmcdo29** [comment]
I think the screenshot is hghlighting the wrong thing here. The code change, I think, is correct though. The `AllExceptionsFilter` in the docs does expect an instance of `HttpAdapterHost` passed to the constructor, but in the code snippet we are pulling out the `httpAdapter` from the `HttpAdapterHost`

```ts
@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  constructor(private readonly httpAdapterHost: HttpAdapterHost) {}

  catch(exception: unknown, host: ArgumentsHost): void {
    // In certain situations `httpAdapter` might not be available in the
    // constructor method, thus we should resolve it here.
    const { httpAdapter } = this.httpAdapterHost;

    const ctx = host.switchToHttp();

    const httpStatus =
      exception instanceof HttpException
        ? exception.getStatus()
        : HttpStatus.INTERNAL_SERVER_ERROR;

    const responseBody = {
      statusCode: httpStatus,
      timestamp: new Date().toISOString(),
      path: httpAdapter.getRequestUrl(ctx.getRequest()),
    };

    httpAdapter.reply(ctx.getResponse(), responseBody, httpStatus);
  }
}
```

```ts

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const { httpAdapter } = app.get(HttpAdapterHost);
  app.useGlobalFilters(new AllExceptionsFilter(httpAdapter));

  await app.listen(3000);
}
bootstrap();
```

**Comment by kamilmysliwiec** [comment]
@jmcdo29 I think it depends on what example we're looking at. The latter one with `AllExceptionsFilter extends BaseExceptionFilter` requires the `HttpServer` while the "custom implementation" needs the `HttpAdapterHost`. We might need to update these examples to make it more consistent

**Pull request closed without merging**
