### PR TITLE
docs(modules.md) - Edits to Modules chapter

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Documentation

## Other information

@kamilmysliwiec Modules chapter proposed edits, for your review.

### CODE REVIEW

**Comment by johnbiundo** [comment]
@kamilmysliwiec 

Quick meta note. Sorry for the slow down last week.

As I work on the advanced topics, I plan to do more research and testing in order to make better contributions. For example, I want to test each code sample to make sure it executes properly.  This is more time consuming (and may generate more questions to you).

After some thought, I decided to keep things moving along for now. So I'll defer that deeper testing/research and continue in "light editing" mode for the time being. As a result I may come back for a second round of editing on some chapters when I've had time to do the additional research. This is not ideal as it may require more of your review time, but I think it's best for now to keep things moving. Welcome any feedback you have on the process.

**Comment by kamilmysliwiec** [comment]
Amazing contribution again, thank you!
One thing that we should clarify:
```
 In small applications, the root module may be the only module in your application.
```
We should rather emphasize that even though it's theoretically possible, it's still not considered to be a good practice.

**Comment by johnbiundo** [comment]
> We should rather emphasize that even though it's theoretically possible, it's still not considered to be a good practice.

I'm on it!

**Comment by kamilmysliwiec** [comment]
Amazing  🔥🔥🔥

**Pull request merged**
