### PR TITLE
update: supplemental guard injection method in the controller

### PR DESCRIPTION
**Pull request by muyu66**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Other... Please describe: Supplementary explanation, the original explanation is not detailed enough, beginner may be not easy to understand
```

## What is the current behavior?

explanation is not detailed enough

Issue Number: N/A

## What is the new behavior?
explanation is detailed enough

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Don't you think that it would bring more confusedness? People might start thinking that putting a guard into `providers` array is required (while it's not true).

**Comment by muyu66** [comment]
If I don't do this, I won't be able to inject any dependencies into the GUARD. "The provide: APP_GUARD" and "execution context" in the original text are not a reasonable solution.

**Comment by kamilmysliwiec** [comment]
You'll be able to do this. Guard shouldn't be added to providers, unless you want to inject **them** somewhere.

**Comment by muyu66** [comment]
Then, if i want to inject Service into GUARD, how to do.

**Comment by kamilmysliwiec** [comment]
Simply inject, same as in controllers/services

**Pull request closed without merging**
