### PR TITLE
[Refactor] TabsComponent to CodeComponent custom element 

### PR DESCRIPTION
**Pull request by BrunnerLivio**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?
In the future, the HTML shall be appended to the DOM dynamically (pre-compile Markdown to HTML using Dgeni, dynamically request the HTML page). The `TabsComponent` is an Angular component - and the easiest way to say to Angular "hey, in this HTML I dynamically loaded is a component", is to simply convert the Angular component to a Custom Element / Webcomponent. Angular.io uses the same technique.
 
Related Issue Number: #549

## What is the new behavior?
Simplified the interface of the code/switcher component & converted it to a custom element.

```html
<code-element filename="cat.service">
  <pre slot="ts" class="language-typescript">
    <code class="language-typescript">
console.log("Hello");
    </code>
  </pre>
  <pre slot="js" class="language-javascript">
    <code class="language-javascript">
console.log("Hello");
    </code>
  </pre>
</code-element>
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
The `[appAnchor]` directive will need to be converted to a native element to enable #549. This will be done in a follow-up PR.

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
With this PR we could also completely remove `@@switch` & `@@filename` markdown syntax sugar. I could improve the PR so it works like MDX:

```markdown

## Here is some code

<code-element>
  <slot name=“js”>
console.log(“Hello World”)
  </slot>
  ...
</code-element>
```

Up to you if you want to keep it :)

**Comment by kamilmysliwiec** [comment]
Perhaps, I'm missing the point. Why do we want to use a custom element in this app?

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec 
> Perhaps, I'm missing the point. Why do we want to use a custom element in this app?

With #549 we want to remove all the `src/app/pages/*` components. This means we request the HTML document (which was generated using the Dgeni Markdown compiler) dynamically.

NestJSdocrequest

Since we dynamically append the content with `innerHTML`, we can't use Angular Component in the generated HTML document (Angular can't render components if it is not a template inside `@Component`-directive). To bypass this we create custom elements beforehand, which enables this

This PR does not bring any value right now, apart from enabling #549. I try to simplify #549, so it is simpler to review.

**Comment by kamilmysliwiec** [comment]
Makes sense now @BrunnerLivio! Thanks for the explanation. I'll review it shortly

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec any plans to revisit this PR sometime soon?

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec passive-aggressive bump #2 :)

**Comment by kamilmysliwiec** [comment]
Finally found some time :) Apologies for the delay!

Great contribution!

**Comment by kamilmysliwiec** [comment]
@BrunnerLivio after merging this PR, I've noticed that some examples are missing.

image

https://docs.nestjs.com/techniques/validation#transform-payload-objects

See the missing code snippet below the `This can be done at a method level:` sentence. :(

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec alright let me into it. Thanks for reverting it real quick!

**Comment by kamilmysliwiec** [comment]
Thanks @BrunnerLivio  🔥 💪

**Pull request merged**
