### PR TITLE
fix: add missing core files in First Steps section

### PR DESCRIPTION
**Pull request by glenwinters**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
```

## What is the current behavior?

The First Steps section doesn't describe all of the files that are generated in `src/`.

Issue Number: N/A

## What is the new behavior?

The table of "core files" is complete.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Screenshot:

image

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
@jmcdo29 would you like to verify :)? grammar wise etc

**Review by jmcdo29 — APPROVED** [review]
LGTM

**Comment by glenwinters** [comment]
Good to merge?

**Comment by kamilmysliwiec** [comment]
Thanks!

**Pull request merged**
