### PR TITLE
docs(controllers.md) Add note on @Res() per #456

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Documentation

## Other information

@kamilmysliwiec Controller page update re: issue #456 for your review.

### CODE REVIEW

**Comment by johnbiundo** [comment]
Fixed bad HTML

**Comment by kamilmysliwiec** [comment]
Should we add some CSS to make this * more visible?

image

**Comment by johnbiundo** [comment]
Agreed!  How about this (proposed new on the right)?
image

Here's a bigger view:
image

Above also has removed `<sup> </sup>` tags, so the * is lower.  Here it is **with** `<sup>` back in:

image

Here's the CSS:
`style="color: #2876d2; font-weight: 700;"`


RE: CSS - I could do it inline, or add a class to `styles.css`.  Or leave it to someone else if they own Docs styles.

**Comment by johnbiundo** [comment]
I think `<sup>` overrode font-weight on last sample.  We could keep the larger size AND just do vertical-align (what `<sup>` does anyway) to get both.

**Comment by kamilmysliwiec** [comment]
Imo this one is the best:

image

(without sup)

> CSS - I could do it inline, or add a class to styles.css.

Feel free to add a class:)

**Comment by johnbiundo** [comment]
Sorry about the multiple commits.  I haven't quite got the hang of squash yet.

**Comment by kamilmysliwiec** [comment]
Np. I can see some conflicting files. Could you resolve them, please? :) @johnbiundo

**Comment by johnbiundo** [comment]
> Np. I can see some conflicting files. Could you resolve them, please? :) @johnbiundo

@kamilmysliwiec should be good now.

**Comment by kamilmysliwiec** [comment]
thank you :)

**Pull request merged**
