### PR TITLE
import fix for new version of socket.io-redis

### PR DESCRIPTION
**Pull request by yharaskrik**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Other... Please describe: Documentation
```

## What is the current behavior?
Trying to import socket.io-redis with 

```
import * as redisAdapter from 'socket.io-redis';
```

results in:

```
const redisAdapter = redisIoAdapter(REDIS_CONNECT_CONFIG);
                     ^
TypeError: redisIoAdapter is not a function
```

## What is the new behavior?

Changing it to 

```
import redisAdapter from 'socket.io-redis';
```

Works and the Nest server starts up correctly.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
I believe that this depends on TypeScript configuration, am I correct?

**Comment by yharaskrik** [comment]
I'm unsure, what flag would change this behaviour?

**Comment by yharaskrik** [comment]
I can play around with a couple different flags this morning and see if I can get it working with the way the example imports it.

**Comment by kamilmysliwiec** [comment]
Oh, so actually I've been thinking about the `allowSyntheticDefaultImports` but this is probably not related to this issue.

**Pull request merged**
