### PR TITLE
Changed header css . Show search bar for smaller resolutions . Solved Issue#1182

### PR DESCRIPTION
**Pull request by psjishnu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[*] Other... Please describe:
```

## What is the current behavior?
Show search bar for smaller resolutions . Solved Issue #1182  

Issue Number: #1182 

## Does this PR introduce a breaking change?
```
[ ] Yes
[*] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
It's broken for a few screen resolutions now: 
image

We want to make sure it looks good even if someone manually resizes the window (which happens quite frequently with the framework/library documentations)

**Comment by psjishnu** [comment]
@kamilmysliwiec  I will repair it

**Comment by psjishnu** [comment]
> It's broken for a few screen resolutions now:
> image
> 
> We want to make sure it looks good even if someone manually resizes the window (which happens quite frequently with the framework/library documentations)

This will be in normal position after complete loading of the page

**Comment by kamilmysliwiec** [comment]
For some reason, I'm still seeing this issue (checked in the incognito mode, just to make sure)

**Comment by psjishnu** [comment]
@kamilmysliwiec   Check out  https://deploy-preview-1243--docs-nestjs.netlify.app/ now . I hope now it is corrected . I just checked out it in incognito mode in firefox and  chrome and it seems to be OK when I checked .

**Comment by psjishnu** [comment]
@kamilmysliwiec Requesting review .

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
