### PR TITLE
docs(subscription.md) correction re: subscription handler name

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

Partially addresses https://github.com/nestjs/graphql/issues/753 by correcting an error and being more explicit about how the published event needs to correspond to the subscription result object.

Doesn't address the [mutation variant](https://github.com/nestjs/graphql/issues/753#issuecomment-611945956) of that issue as that seems like a corner case, and when I tried to explain it, I felt it was more confusing than helpful.

### CODE REVIEW

**Comment by josh18** [comment]
Looks good :+1:

Rather than
> The above requirement can create undesired coupling between the `@Subscription()` method handler name (`commentAdded()`) and the event payload. To specify a name for the subscription that is independent of the method handler name, use the `name` option in the `@Subscription()` decorator:

I wonder if it would be clearer to note that the payload key must match the GraphQL Subscription name? If you don't define this name explicitly using the name option, then the name will be inherited from the name of the subscription handler. Just so it is obvious that they are two different concepts.

> Doesn't address the mutation variant of that issue as that seems like a corner case, and when I tried to explain it, I felt it was more confusing than helpful.

Are you talking about the resolve option? If so I think all that we need to say is that if you are using the resolve option you must return the unwrapped payload.

❌ 
```
@Subscription(returns => Comment, {
  resolve: payload=> payload,
})
commentAdded() { ... }
```

✔️
```
@Subscription(returns => Comment, {
  resolve: payload=> payload.commentAdded,
})
commentAdded() { ... }
```
We might want to update some of the examples to reflect that as well

**Comment by johnbiundo** [comment]
@josh18 Take a look.  I think this is an improvement -- though not exactly what you suggested.

I didn't notice your comment about examples until after I pushed this.  Gotta run for now, but take a look and I can make final changes tomorrow. Thanks for your help.

**Comment by josh18** [comment]
Yup I think that's good :+1:

**Comment by johnbiundo** [comment]
@kamilmysliwiec I think this is ready for your review.

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
