### PR TITLE
Fix the terminus example code

### PR DESCRIPTION
**Pull request by BrunnerLivio**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?
Some code examples of the nestjs/terminus integration are faulty.

## What is the new behavior?
Fixed the faulty code examples and added javascript code examples in addition

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by gperdomor** [comment]
I have a HealthModule:

```
export class TerminusOptionsService implements TerminusOptionsFactory {
  constructor(private readonly dns: DNSHealthIndicator) {}

  createTerminusOptions(): TerminusModuleOptions {
    const healthEndpoint: TerminusEndpoint = {
      url: '/health',
      healthIndicators: [async () => this.dns.pingCheck('google', 'https://google.com')],
    };
    return {
      endpoints: [healthEndpoint],
    };
  }
}

@Module({
  imports: [
    TerminusModule.forRootAsync({
      useClass: TerminusOptionsService,
    }),
  ],
})
export class HealthModule {}
```

and my app.module.ts:

```
@Module({
  imports: [
    ConfigModule.load(resolve(__dirname, 'config', '!(*.d).{ts,js}'), {
      path: `${process.env.NODE_ENV || 'development'}.env`,
    }),
    RedisModule.forRootAsync({
      useFactory: (config: ConfigService) => config.get('redis'),
      inject: [ConfigService],
    }),
    HealthModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

but alway get `TypeError: Cannot read property 'pingCheck' of undefined`

**Comment by BrunnerLivio** [comment]
@gperdomor The new proposed code snippets in this PR should fix this :)

```ts

@Injectable() // <-- Injectable decorator has been missing
export class TerminusOptionsService implements TerminusOptionsFactory {
...
}
```

Otherwise have a look at [sample/000-dogs-app](https://github.com/nestjs/terminus/tree/master/sample/000-dogs-app). It is as close as possible to the new doc example!

**Comment by gperdomor** [comment]
@BrunnerLivio thanks 👍

**Comment by kamilmysliwiec** [comment]
Could you please resolve conflicts (remove auto-generated HTML files - I have just excluded them from repository)? 🙂

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec done :)

**Comment by kamilmysliwiec** [comment]
Thank you @BrunnerLivio 🤗

**Pull request merged**
