### PR TITLE
GRPC Advanced Protobuf concepts and Streaming handler docs

### PR DESCRIPTION
**Pull request by anton-alation**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently, documentation lacks descriptions for GRPC streaming cases. As well docs aren't describing possible resolutions for sophisticated cases of `protobuf` API definitions.

Mentions in issue: [1286](https://github.com/nestjs/nest/issues/1286)
Mentions in PR: [1586](https://github.com/nestjs/nest/pull/1568)
Mentions in PR: [1733](https://github.com/nestjs/nest/pull/1733)

## What is the new behavior?

Docs describing:
- Protobuf and namespaces
- GRPC stream handlers

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Would it be possible to split this PR into 2 separate ones? (first one with just streaming and the second one with advanced use cases) It should be easier to discuss these parts separately (+ I'd love to merge streaming part as soon as possible :))

**Comment by anton-alation** [comment]
> Would it be possible to split this PR into 2 separate ones? (first one with just streaming and the second one with advanced use cases) It should be easier to discuss these parts separately (+ I'd love to merge streaming part as soon as possible :))

@kamilmysliwiec Certainly. Let me get through that over the weekend and by Monday to have 2 PRs for 2 parts.

**Comment by kmturley** [comment]
This documentation seems to be wrong?

In your feature integration tests you have the code returning a Promise:

```
@GrpcStreamMethod('Math')
async sumStream(messages: Observable<any>): Promise<any> {
  // Form a resulting promise
  return new Promise<any>((resolve, reject) => {
    // Subscribe for a message to for a test answer
    messages.subscribe(msg => {
      // Resolve with reduce function
      resolve({
        result: msg.data.reduce((a, b) => a + b),
      });
    }, err => {
      reject(err);
    });
  });
}
```
https://github.com/anton-alation/nest/blob/c26bbbb9bcdf8d72865dd310e5811585b5f1a719/integration/microservices/src/grpc/grpc.controller.ts#L35

But in your documentation you have it returning an Observable:
```
@GrpcStreamMethod('orders.OrderService')
async sync(messages: Observable<any>): Observable<any> {
  const s = new Subject();
  const o = s.asObservable();
  messages.subscribe(msg => {
    s.next({
      id: 1,
      itemTypes: [1],
      shipmentType: {
        from: 'test',
        to: 'test1',
        carrier: 'test-carrier',
      },
    });
  });
  return o;
}
```
https://github.com/nestjs/docs.nestjs.com/pull/378/files#diff-fe644df738960311de63d1e747b0dbacR429

I believe the Promise version is accurate, as you can't return an Observable from an async function?

**Comment by anton-alation** [comment]
@kmturley Yeah I believe it should be updated to `Promise<Observable<any>>`, my bad. I'll be updating those, thank you for pointing.

**Comment by kamilmysliwiec** [comment]
We've got 2 separate PRs for this now. Closing then

**Pull request closed without merging**
