### PR TITLE
Update caching example conforming to the new cache-manager-redis-store interface

### PR DESCRIPTION
**Pull request by dabroek**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

Solution as described by the author [here](https://github.com/dabroek/node-cache-manager-redis-store/issues/40#issuecomment-1281407219).

### CODE REVIEW

**Comment by conioX** [comment]
when this pr merge @dabroek ?

**Comment by kamilmysliwiec** [comment]
Apologies for not looking at this PR sooner. There are some new conflicts, could you take a look?

**Comment by nopitown** [comment]
Is there a plan to merge this soon? The documentation is a bit misleading with the latest updates. Thank you.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/2703

**Pull request closed without merging**
