### PR TITLE
docs(sample/11) update docs to reflect the changes of the Swagger example

### PR DESCRIPTION
**Pull request by LukvonStrom**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Documentation to the changes made in the following PR: https://github.com/nestjs/nest/pull/1481

## What is the new behavior?
New Screenshot + 2 Code Samples

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by LukvonStrom** [comment]
fixes https://github.com/nestjs/docs.nestjs.com/issues/135

**Comment by kamilmysliwiec** [comment]
Thanks for your contribution! However, every page has been moved to the markdown syntax now (`content` directory) which makes this PR outdated. Could you please update it?

**Comment by LukvonStrom** [comment]
@kamilmysliwiec I updated the fork, and implemented the changes in the markdown file. Is the Markdown compiled by a script?

**Comment by gkirill** [comment]
Planning to merge this? Had to dig through a bunch of internet to find this description because it is not present in the official docs.

**Pull request merged**
