### PR TITLE
docs(mongo): added section for virtual propertys

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Docs
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, added section for virtual propertys with mongoose. It would be an interesting addition to show.

### CODE REVIEW

**Comment by Tony133** [comment]
to be evaluated :-) NestJS ♥️

**Comment by kamilmysliwiec** [comment]
What's the reason for adding mongoose specific features to NestJS docs when the way you use them doesn't change regardless of whether you use Nest or not?

**Comment by Tony133** [comment]
I agree that how you use it is independent of whether you use Nest or not, but it could help, very useful even for beginners using Nest with mongoose for the first time or have never done so.
And a proposal since I noticed that even the Discriminators section if I'm not wrong and independent if you use Nest or not, I thought that a little hint on virtuals with Nest might be useful.

Then for the rest, as always, there is the official mongoose guide.

I take this opportunity to thank you for creating NestJS ♥ ️, a fantastic framework, as you can see I am trying to help you where there is opportunity both here and in the discord channel. If you need a hand on me you can count. 😀👍

**Comment by kamilmysliwiec** [comment]
> And a proposal since I noticed that even the Discriminators section if I'm not wrong and independent if you use Nest or not, I thought that a little hint on virtuals with Nest might be useful.

Discriminators, although being a Mongoose feature, have their dedicated section because there's a specific, recommended way of how you could configure them with Nest. The way you register virtual, on the other hand, doesn't differ at all so in this case, I have to close this PR.

> I take this opportunity to thank you for creating NestJS ♥ ️, a fantastic framework, as you can see I am trying to help you where there is opportunity both here and in the discord channel. If you need a hand on me you can count. 😀👍

Thank you and thank you for your help & commitment and all the contributions so far! 🙂

**Pull request closed without merging**
