### PR TITLE
chore(): upgrade angular v16

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Proposal:

- Upgrade to Angular v16 🔥
- Upgrade to Typescript v5 🔥
- Removed unused configurations and deprecated
- Removed the empty and unused `style.css` and `app.component.css` files.
- Changed imports in sass files, now from now on it is better to use `@use` instead of `@import`, in the future it will be removed see here: https://sass-lang.com/documentation/at-rules/import
- Removed the `ngx-perfect-scrollbar` dependency related to sidebar scrolling, because it is deprecated and no longer compatible with new and even future versions of Angular, due to the new Ivy compiler that has now become the default Angular compiler replacing the old compiler (see screenshot). 

screen-library-scroll

-  Updated the version of nodejs in the configuration of CI( see commit here: https://github.com/nestjs/docs.nestjs.com/pull/2725/commits/3cc47651a96c06df5ca7d41325f2c7a87f13fef7), the 12.x version of Nodejs has done its time 😄, I configured the 16.x version of NodeJS 🙌

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

At the moment to replace the `ngx-perfect-scrollbar` dependencies, I configured simple css rules to do the scroll in the sidebar if I find other solutions later I will post them in a comment, currently comes in this way the side-bar scroll ( see screenshot)

screen-side-bar

Below I attach my branch to try it locally:

```
git clone https://github.com/Tony133/docs.nestjs.com
```
```
git checkout chore/upgrade-angular-v16 
```
or 

```
git switch chore/upgrade-angular-v16
```

### CODE REVIEW

**Comment by Tony133** [comment]
A small update on this PR:
  - I resolved conflicts
  - Updated imports on sass files
  - Removed empty files that were not needed.

However, I have also updated the list of changes above with the latest changes 🙌

For a preview of the site as it is now based on the changes made in this PR, see here: https://deploy-preview-2725--docs-nestjs.netlify.app/ ( netlify generated link for a preview 🙌)

**Comment by kamilmysliwiec** [comment]
Current version:

image

This PR:

image

If we can't use `ngx-perfect-scrollbar` anymore - that's fine, but we need to make sure the new version visually & functionally aligns with what we currently have.

**Comment by Tony133** [comment]
I did a little update, now is more aligned, It looks a lot like the one used with the`ngx-perfect-scrollbar` package. (see screenshot).
Preview with the latest changes I've made: https://deploy-preview-2725--docs-nestjs.netlify.app/  

What do you think? that might be okay ?

scroll-bar-new

**Comment by Tony133** [comment]
Hi 👋🏻, 

I am writing below some updates I have made:

- fixed the conflicts
- updated the version of Angular to 16.1.x 
- removed some js files that are not used

for the scroll I fixed it and it is very similar to the one used with the ngx-perfect-scrollbar package, I attach the link for the preview generated by netlify: https://deploy-preview-2725--docs-nestjs.netlify.app/

I know these days we are busy upgrading packages and apps to NestJS v10 ♥️😻🚀, anyway as soon as you find some time let me know if you like it.  😉

**Comment by kamilmysliwiec** [comment]
Great job @Tony133, thank you 🚀 🔥

**Comment by kamilmysliwiec** [comment]
I had to temporarily revert this PR @Tony133. Code snippets stopped working, see the screenshot below:

image

**Comment by Tony133** [comment]
I think it's `prismjs`, I'll take a look at it today 💪

**Pull request merged**
