### PR TITLE
docs: change wording of datasource injection scope

### PR DESCRIPTION
**Pull request by mango-martin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
The current wording is a bit confusing. A `project` to me means all the files in the repo. If you think about it, it's obvious that this behavior can't apply to any random file. But by changing the wording a bit I hope it gets clearer as to where the line is actually drawn.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
IMO this sounds more confusing. cc @jmcdo29 @micalevisk what do you tihnk?

**Comment by micalevisk** [comment]
I think that 'entire project' is fine. Or even 'entire NestJS app'

**Comment by jmcdo29** [comment]
I think the fact that we already mention it will be available to "inject" should imply that this is specifically where DI is possible. I wouldn't expect to inject a value into a class that Nest isn't managing for me.

**Comment by mango-martin** [comment]
Just a suggestion. Feel free to close it, of course.

But if I may I want to add that 
> I think the fact that we already mention it will be available to "inject" should imply that this is specifically where DI is possible. I wouldn't expect to inject a value into a class that Nest isn't managing for me.

This statement in the docs, that you do NOT have to inject it, is partly where the confusion comes from. For anyone who's dealt with Nest for a long time, they read these lines and they know exactly what's going on. But a newcomer might be left confused when they try to use this in a file that they think is "within the project" but then it doesn't work as expected.

**Comment by mango-martin** [comment]
Just a suggestion, feel free to close this, of course.

**Pull request closed without merging**
