### PR TITLE
fix(a11y): make the menu button accessible

### PR DESCRIPTION
**Pull request by dianjuar**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

The menu button is not accessible by the keyboard.

old

## What is the new behavior?

The menu now is accessible by keyboard

new

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Amazing contribution @dianjuar, thank you!

One note: could we remove the outline on **click**?

image

**Comment by dianjuar** [comment]
> Amazing contribution @dianjuar, thank you!
> 
> One note: could we remove the outline on **click**?
> 
> image

You are right, I'll do it

**Comment by kamilmysliwiec** [comment]
@dianjuar any chance you can look into this in the next few weeks 💪 ?

**Comment by dianjuar** [comment]
Yes, for sure.
I don't want to let this PR die.

**Comment by dianjuar** [comment]
Hi @kamilmysliwiec 
It's a chromes behavior, that's the way chrome manages the focus of a button without background
```css
background: none;
```
Prove that buttons without background always mark the outline when is focused

chrome-prove

If you look the page with a different browser if has the expected behavior

**Firefox**

firefox

**Comment by dianjuar** [comment]
It can be done but it's not [that straight forward](https://www.kizu.ru/keyboard-only-focus/).
I think it worth the effort.

**Comment by kamilmysliwiec** [comment]
@dianjuar it seems that Angular docs (https://angular.io/docs) have a different CSS applied on focus:

image

vs

image

Could we do something similar instead of having this blue outline?

**Comment by dianjuar** [comment]
In the Angular official web page, they have that behavior because they are using AngularMaterial, it normalizes all the focus look and feel to look very similar across all the browsers using javascript and custom CSS classes to achieve that behavior.

I would have to implement CSS classes and custom directives to achieve that behavior or use AngularMaterial buttons to achieve that behavior.

angular material

**Pull request closed without merging**
