### PR TITLE
docs(common): request lifecycle

### PR DESCRIPTION
**Pull request by jmcdo29**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently there are no docs on the Request Lifecycle.

Issue Number: N/A

## What is the new behavior?

A new docs pages under the `FAQ` section about the request lifecycle.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

The question about how the request flows through the application has come up several times on Discord and StackOverflow, so I figured I would take some time to document it, at least for HTTP and GraphQL (though Websockets and Microservices in theory should follow the same pattern). Thanks to @johnbiundo for giving the docs a first look before I made a PR.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Thanks!

I'm wondering, maybe we should move this under Fundamentals instead? What do you think?

**Comment by jmcdo29** [comment]
I put in in FAQ for the moment as I've seen the question asked a lot. I can move it to Fundamentals no problem if that's where you'd prefer it!

**Comment by johnbiundo** [comment]
No strong feeling either way about Fundamentals vs. FAQ, but I guess I would vote for FAQ.

**Comment by kamilmysliwiec** [comment]
Thanks for your input @johnbiundo. Let's stay with FAQ then.

@jmcdo29 thanks again for the great contribution! :)

**Pull request merged**
