### PR TITLE
chore(): Make the generated html file be ignored

### PR DESCRIPTION
**Pull request by Karibash**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Fix the html file generated after the build so that changes to it are not detected.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Karibash** [comment]
I am getting errors in CI due to unused pages being committed, is it ok to delete them?

unused page: https://github.com/nestjs/docs.nestjs.com/tree/master/src/app/homepage/pages/advanced/mixin-components
routing: https://github.com/nestjs/docs.nestjs.com/blob/master/src/app/app-routing.module.ts

**Comment by kamilmysliwiec** [comment]
> It appears that an error occurs at build time due to the presence of unused pages.
May I delete them?

Sounds good!

**Comment by Karibash** [comment]
@kamilmysliwiec 
I can confirm that the build is successful!

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
