### PR TITLE
 docs(plugins) ts-jest integration docs for graphql and swagger

### PR DESCRIPTION
**Pull request by Larinel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[X] Docs
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```
## Other information
While implementing e2e tests for nest graphql server, I run into issue with compiling graphql schema using plugin.
I spent some time searching for a workaround and found it. Thought it is worth documenting.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
@jmcdo29  Would you be able to review (grammar wise etc)? :)

**Review by jmcdo29 — APPROVED** [review]
Looks good to me. I actually wrote an article on a different approach that has the same outcome, but this is much easier to work with.

**Comment by Larinel** [comment]
Is there any updates on this?

**Comment by kamilmysliwiec** [comment]
@Larinel could you add the same section to the OpenAPI docs (plugin chapter)?

**Comment by Larinel** [comment]
@kamilmysliwiec like this?

**Comment by kamilmysliwiec** [comment]
Thanks!

**Pull request merged**
