### PR TITLE
docs(caching): TTL in ms as from cache-manager@^5

### PR DESCRIPTION
**Pull request by alexismch**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

In caching doc, the TTL is defined in seconds.

Issue Number: N/A

## What is the new behavior?
As from cache-manager@^5, the TTL is defined in milliseconds.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by micalevisk** [comment]
in the latest version of `@nestjs/common`, the `ttl` opt is still in seconds regardless of the version of `cahe-manager`. See: https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/packages/common/cache/cache.providers.ts#L25-L32 (if it is v5+ that option is multiplied by 1000)

**Comment by alexismch** [comment]
> in the latest version of `@nestjs/common`, the `ttl` opt is still in seconds regardless of the version of `cahe-manager`. See: https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/packages/common/cache/cache.providers.ts#L25-L32 (if it is v5+ that option is multiplied by 1000)

@micalevisk As seen in the code you linked, the TTL is multiplied by 1000 only for the default option, not for the passed one.
I refer as well to the CacheManagerOptions (c.f. https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/packages/common/cache/interfaces/cache-manager.interface.ts#L72-L78) comment that states the same words as my patch.

**Comment by alexismch** [comment]
@micalevisk can you please review my last comment and maybe reconsider my PR? Thanks

**Comment by micalevisk** [comment]
@alexismch yeah, you were correct. Can't you reopen this?

**Comment by alexismch** [comment]
@micalevisk thank you for your return. Sadly it seems not, I think only @kamilmysliwiec can do so

**Comment by micalevisk** [comment]
tbh I'd prefer if we change that to always be in seconds. But then it would introduces breaking changes :/ that's why we should document it here

**Pull request closed without merging**
