### PR TITLE
Add required package swagger-ui-express to swagger install docs

### PR DESCRIPTION
**Pull request by kiwikern**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
```

## What is the current behavior?
Since nestjs/swagger#218, swagger-ui-express has to be installed manually when using express. When it is not installed, you get the message `The "swagger-ui-express" package is missing. Please, make sure to install this library ($ npm install swagger-ui-express) to take advantage of SwaggerModule.` This change should be reflected in the docs.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Perhaps, we should also add a note what package is required when `fastify` is being used?

**Comment by micaelmbagira** [comment]
A PR with the same fix existed already https://github.com/nestjs/docs.nestjs.com/pull/312

**Comment by kiwikern** [comment]
@kamilmysliwiec Good point, I've just added the fastify case.

@micaelmbagira Great minds think alike, I guess. ;-) I checked if one existed before I started working on it but during these 20 minutes you apparently posted yours. You can also work out the changes with Kamil on your pull request, I don't mind. :-)

**Comment by kamilmysliwiec** [comment]
I can see that #312 has been closed. Would you like to add missing information to this PR @kiwikern then? :)

**Comment by kiwikern** [comment]
@kamilmysliwiec I added the fastify package in the commit two days ago. Is anything else missing?

**Comment by kamilmysliwiec** [comment]
Thank you :)

**Comment by abinhho** [comment]
@kamilmysliwiec Which version has been fixed this issue? I still got this issue with latest version
```
"dependencies": {
    "@nestjs/common": "^7.1.0",
    "@nestjs/core": "^7.1.0",
    "@nestjs/passport": "^7.0.0",
    "@nestjs/platform-express": "^7.0.7",
    "@nestjs/swagger": "^4.5.8",
    "aws-serverless-express-binary": "^1.0.1",
    "class-transformer": "^0.2.3",
    "class-validator": "^0.11.1",
    "dayjs": "^1.8.24",
    "dotenv": "^8.2.0",
    "dynamodb-data-types": "^3.0.1",
    "express": "^4.17.1",
    "faker": "^4.1.0",
    "jest": "^24.9.0",
    "jwks-rsa": "^1.6.0",
    "latinize": "^0.4.1",
    "lodash": "^4.17.15",
    "mime-types": "^2.1.26",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.3",
    "serverless-dynamodb-local": "^0.2.39",
    "swagger-ui-express": "^4.1.4",
    "tslint-loader": "^3.5.4",
    "uuid": "^3.3.3",
    "winston": "^3.2.1"
  },
```

Local worked but deploy into `serverless` got error.

**Pull request merged**
