### PR TITLE
docs(): add new feature of ConfigService on configuration page

### PR DESCRIPTION
**Pull request by micalevisk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

No documentation regarding the feature that will be introduced in `@nestjs/config` after merging https://github.com/nestjs/config/pull/676

## What is the new behavior?

<details>
<summary>screenshots</summary>

image

image

</details>

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
@jmcdo29 if you can check this out that would be great 🙌

**Review by jmcdo29 — CHANGES_REQUESTED** [review]
Overall looks good. Made a few small suggestions

**Review by jmcdo29 — APPROVED** [review]
LGTM

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
