### PR TITLE
docs(sql): fix custom repository example code in module

### PR DESCRIPTION
**Pull request by TMantas**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
[ ] Other... Please describe:
```

## What is the current behavior?
The current example of using custom repositories doesn't work. `TypeOrmModule.forFeature()` accepts entities but not repositories.

Issue Number: N/A

## What is the new behavior?
Updated docs by providing code example which uses custom repository in providers.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jmcdo29** [comment]
Custom repositories need to be added to the TypeORM context, as they have properties in the constructor that Nest inherently doesn't understand (connection, entity manager, etc). Using Custom Repositories as providers directly, to my understanding, does not work.

**Comment by TMantas** [comment]
hey @jmcdo29 thanks for commenting. well, I'm relatively new to the framework so I might be missing something. I also realised that my situation might be edge case.
have a look at test repo I created: https://github.com/TMantas/nestjs-custom-repository-test
the situation is that I don't have any entities (as for now) so when I try to create custom repository without extends, I get this error: 
```
No repository for "CustomRepoRepository" was found. Looks like this entity is not registered in current "default" connection?
RepositoryNotFoundError: No repository for "CustomRepoRepository" was found. Looks like this entity is not registered in current "default" connection?
```

that's why I decided to try moving `CustomRepoRepository` to `providers` and it seems to work that way.

**Comment by jmcdo29** [comment]
You have a custom Repository without an entity? Seems counter intuitive. Custom repos are supposed to build onto existing Repository classes. Anyways, for more support, please visit our [Discord](https://discord.gg/NestJS)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Pull request closed without merging**
