### PR TITLE
docs(dynamic-modules) - Create new Dynamic Modules chapter

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Documentation

## Other information

@kamilmysliwiec Proposed new Dynamic Modules chapter for your review.

Associated example PR on nest repo to follow soon.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Amazing work! I'll merge once we fix these issues https://github.com/nestjs/nest/pull/2911 :))

**Comment by kamilmysliwiec** [comment]
One small thing that I'm concerned about - isn't `ModuleMetadata` a bit too complex (to include it in the chapter).

**Comment by johnbiundo** [comment]
@kamilmysliwiec I simplified the explanation of the interface.  We could further trim/abstract the interface if you think it needs it.  Otherwise, if you'd prefer to remove this portion of the discussion and describe it without showing the interface, let me know.

**Comment by kamilmysliwiec** [comment]
Hmm.. I'm still wondering if we shouldn't just remove this interface and mention something like - `DynamicModule` has one extra property `module` more than options object passed into the `@Module()` decorator (but wrapped with better words ;)) Some people may not be familiar with `Type` for instance which makes it more complex from the developer standpoint

**Comment by johnbiundo** [comment]
Sure, I can make that change.  I understand your point.  I'll get to that a bit later today.

**Comment by kamilmysliwiec** [comment]
Amazing, thank you!

**Comment by johnbiundo** [comment]
Updated.  Hopefully we've wrestled this beast to the ground! 😉

**Comment by kamilmysliwiec** [comment]
Thank you 💪

**Pull request merged**
