### PR TITLE
docs(first-steps): update nodejs minimum version to v14

### PR DESCRIPTION
**Pull request by micalevisk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

See https://github.com/nestjs/nest/issues/9354

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Tony133 — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
Nest should still work fine on v10.13.0 (although it's not an LTS version). What's the reason for this (breaking) change?

**Comment by Tony133** [comment]
@kamilmysliwiec, it turned out that with version 10.13 the app crashed [see problem here](https://github.com/nestjs/nest/issues/9354), the problem was solved by updating the version of nodejs and we thought that since version 10.13 which later became LTS see [here] (https://nodejs.org/ru/blog/release/v10.13.0/) its maintenance cycle is finished (end of life) and since nodejs version 12 also ends maintenance next month, we thought about updating the documentation with a version 14 of Nodejs as it is still under maintenance for some time or an LTS version.

This is a brief summary of the why of this PR. 😁

**Comment by kamilmysliwiec** [comment]
I just double-checked and Nest works as expected with Node v10.13.

image

Requirement !== recommendation. 

We recommend everyone to use most recent & stable versions (at least LTS) but this doesn't mean Nest isn't compatible with older releases.

**Comment by Tony133** [comment]
Right, I agree  `Requirement !== recommendation` 👍

I usually always use LTS as the nodeJS version. 😄

I'll let you notice one thing, look at this minimal reproduction `https://github.com/AmrAbdalrahman/test-nest` gives error with 10.13 while going to 16.13.1 it works and look at these screenshots i did a clean installation from scratch with version 10.13.0 and then I switched to 16.13.1 and it only works with 16.13.1.


screenshot

From what I understand the error is only with a clean installation of Nest using nodejs 10.13, but I will do more tests. By any chance it gives you an error while installing clean with nodejs 10.13?

**Pull request closed without merging**
