### PR TITLE
Add discord icon

### PR DESCRIPTION
**Pull request by BrunnerLivio**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?
No discord icon

Issue Number: #376

## What is the new behavior?
- Adds discord icon
- Move social-wrapper div into own component

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec I have moved the social-wrapper into its own component to increase the readability. Should this component also be used in the footer? Note: The social links differ in the footer (there is a facebook link, which is not present in the header)

**Comment by kamilmysliwiec** [comment]
>  I have moved the social-wrapper into its own component to increase the readability. 

that's totally fine @BrunnerLivio 

one thing to note: we're getting CI issues (you probably added git submodule by accident)

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec fixed!

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
