### PR TITLE
docs(exception-filters): add sample how to use global filter using base filter

### PR DESCRIPTION
**Pull request by cyril-lakech**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Other... Please describe: Documentation
```

## What is the current behavior?

Doc explains not to instanciate a filter extending base filter and to always use annotations to inject

## What is the new behavior?

you can use a base filter and instance it yourself to use it as a global filter

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
> Doc explains not to instanciate a filter extending base filter and to always use annotations to inject

It still applies to the cases where you want to tie filter to a certain method/class. Are you sure that we should remove this warning?

**Comment by cyril-lakech** [comment]
yes you are right, this should stay for this use case

**Comment by cyril-lakech** [comment]
you may squash this with added commit

**Comment by kamilmysliwiec** [comment]
Thanks!

**Pull request merged**
