### PR TITLE
fix(): update advertising banner css style

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [x] Other... Please describe:

## What is the current behavior?

Issue Number:
 - https://github.com/nestjs/docs.nestjs.com/issues/2869 
- https://github.com/nestjs/docs.nestjs.com/issues/2921
- https://github.com/nestjs/docs.nestjs.com/issues/2941

## What is the new behavior?
Proposal:

- Update advertising banner css style

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
Before:

screen-before-advertising-banner

After ( with fix ):

screen-fix-ok

screen-fix

### CODE REVIEW

**Comment by Tony133** [comment]
Link for preview: https://deploy-preview-2922--docs-nestjs.netlify.app/techniques/database 🔥

**Review by micalevisk — APPROVED** [review]

**Review by rubiin — APPROVED** [review]

**Review by smith558 — APPROVED** [review]

**Review by smith558 — CHANGES_REQUESTED** [review]
I don't think this is a fix. Looking at the preview, this proposed change hides the ads until the user scrolls all the way down, making them essential unreachable (which is obviously undesirable).

**Comment by Tony133** [comment]
@smith558  other solutions are always accepted, if you have another solution please post it here.

**Comment by smith558** [comment]
> @smith558 other solutions are always accepted, if you have another solution please post it here.

Unfortunately I do not have time currently. But I am just saying. This proposed way of fix would lead to very much decreased income from the Carbon ads placed on the website because they track "[impressions](https://www.adjust.com/glossary/impression/)".

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/commit/c09208e9588f038a4dfc7ab5283f388dc143ba15

**Pull request closed without merging**
