### PR TITLE
docs(hot-reload): update hot-reload.md

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: 1554

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, update docs hot-reload,  reference: https://github.com/nestjs/docs.nestjs.com/issues/1554 

it also improves the documentation on how to install webpack 5.x and yarn

### CODE REVIEW

**Comment by Tony133** [comment]
reference issue --> https://github.com/nestjs/docs.nestjs.com/issues/1554

**Comment by Tony133** [comment]
@kamilmysliwiec, could this fix in the documentation be fine?

**Comment by therealstein** [comment]
Solution doesn't work for me...
`TypeError [ERR_INVALID_ARG_TYPE]: The "modulePath" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
 `

**Comment by Tony133** [comment]
@therealstein If you have any solution come to solve let me know, they are always well accepted

If you expect such a string you have tried:
```
  new webpack.WatchIgnorePlugin ("/ \. js $ /, /\.d\.ts$/"),
```

**Comment by Tony133** [comment]
I add a reference which may be helpful to this problem: ---> https://github.com/nestjs/nest/issues/5706

**Comment by Tony133** [comment]
I've done some tests

if you use nest 7.5, use webpack 5 and the solution is correct but you need to install
```start-server-nestjs-webpack-plugin``` instead of ```start-server-webpack-plugin````

Installation:

```$ npm i --save-dev webpack-node-externals start-server-nestj-webpack-plugin```

and create file webpack-hmr.config.js

```
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');
const StartServerPlugin = require('start-server-nestjs-webpack-plugin');

module.exports = function(options) {
  return {
    ...options,
    entry: ['webpack/hot/poll?100', options.entry],
    externals: [
      nodeExternals({
        allowlist: ['webpack/hot/poll?100'],
      }),
    ],
    plugins: [
      ...options.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
          paths: [/\.js$/, /\.d\.ts$/]
      }),
      new StartServerPlugin({ name: options.output.filename }),
    ],
  };
};
```

In package.json change "npm start: dev" like so:

"start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js"

**Comment by Tony133** [comment]
@kamilmysliwiec  Isn't it better to specify this in the documentation?
Here, too, you specified the problem   ---> nestjs/nest#5706

**Comment by therealstein** [comment]
> start-server-nestj-webpack-plugin
thanks.
Oh yes no more error with `npm install --save-dev start-server-nestjs-webpack-plugin` but Hot Reload doesnt work as expected.
No reload will triggered after file change/save.

**Comment by Tony133** [comment]
added some warnings in the hot reload page for using webpack 5.x and Yarn, without overwhelming anything he hoped it would go well :-)

**Comment by Superoryco** [comment]
For me, using webpack 5.9.0

1. remove watch: true in webpack-hmr.config.js
2. add --watch to package script: "start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch"

The latest webpack 5.11.1 webpack will throw "The 'compilation' argument must be an instance of Compilation" Error.

**Comment by Tony133** [comment]
tested now for webpack 5.9.0  
I confirm.

I updated the pull with the scripts.

@Superoryco thank you for your reporting

**Comment by Tony133** [comment]
Let's recap:

For configuration `webpack-hmr.config.js`:

``` npm i --save-dev webpack-node-externals start-server-nestjs-webpack-plugin```

or 

``` npm i --save-dev webpack-node-externals  run-script-webpack-plugin webpack```

for yarn 

``` yarn add -D webpack-node-externals run-script-webpack-plugin webpack ```

If you use the yarn 2, instead of installing `webpack-node-externals`, you should install` webpack-pnp-externals`

Configuration for Yarn 2:

```typescript
const webpack = require('webpack');
const { WebpackPnpExternals } = require('webpack-pnp-externals');
const { RunScriptWebpackPlugin } = require('run-script-webpack-plugin');
module.exports = function(options) {
  return {
    ...options,
    entry: ['webpack/hot/poll?100', options.entry],
    externals: [
      WebpackPnpExternals({
        exclude: ['webpack/hot/poll?100'],
      }),
    ],
    plugins: [
      ...options.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
        paths: [/\.js$/, /\.d\.ts$/]
      }),
      new RunScriptWebpackPlugin({ name: options.output.filename }),
    ],
  };
};
```



If you are using one of the latest versions of NestJS, webpack 5.x is used, instead of installing `start-server-webpack-plugin`, you should install `start-server-nestjs-webpack-plugin` or `run-script-webpack-plugin webpack`

Once the installation is complete.

To create the `webpack-hmr.confi.js` configuration file the configuration is the following:

```typescript
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');
const StartServerPlugin = require('start-server-nestjs-webpack-plugin');

module.exports = function(options) {
  return {
    ...options,
    entry: ['webpack/hot/poll?100', options.entry],
    externals: [
      nodeExternals({
        allowlist: ['webpack/hot/poll?100'],
      }),
    ],
    plugins: [
      ...options.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
        paths: [/\.js$/, /\.d\.ts$/]
      }),
      new StartServerPlugin({ name: options.output.filename }),
    ],
  };
};
```

Add script to your `package.json` file:

`"start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch"` 




For configuration `webpack.config.js`:

```npm i --save-dev webpack webpack-cli webpack-node-externals ts-loader run-script-webpack-plugin``` 

for yarn 

``` yarn add -D webpack webpack-cli webpack-pnp-externals ts-loader run-script-webpack-plugin ```

If you use the yarn 2, instead of installing `webpack-node-externals`, you should install` webpack-pnp-externals` 

Configuration yarn 2:


```typescript
const webpack = require('webpack');
const path = require('path');
const { WebpackPnpExternals } = require('webpack-pnp-externals');
const { RunScriptWebpackPlugin } = require('run-script-webpack-plugin');
module.exports = {
  entry: ['webpack/hot/poll?100', './src/main.ts'],
  target: 'node',
  externals: [
    WebpackPnpExternals({
      exclude: ['webpack/hot/poll?100'],
    }),
  ],
  module: {
    rules: [
      {
        test: /.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  mode: 'development',
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new RunScriptWebpackPlugin({ name: 'server.js' }),
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'server.js',
  },
};
```

To create the `webpack.config.js` configuration file the configuration is the following:
```typescript
const webpack = require('webpack');
const path = require('path');
const nodeExternals = require('webpack-node-externals');
const { RunScriptWebpackPlugin } = require('run-script-webpack-plugin');

module.exports = {
  entry: ['webpack/hot/poll?100', './src/main.ts'],
  target: 'node',
  externals: [
    nodeExternals({
      allowlist: ['webpack/hot/poll?100'],
    }),
  ],
  module: {
    rules: [
      {
        test: /.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  mode: 'development',
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new RunScriptWebpackPlugin({ name: 'server.js' }),
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'server.js',
  },
};
```

Add script to your `package.json` file 

```
"start:dev": "webpack --config webpack.config.js --watch"
```

Hope it helps to understand better while waiting for a reviewers.

**Comment by Superoryco** [comment]
@Tony133 by the way, why `new RunScriptWebpackPlugin({ name: 'server.js' })`? not `name: 'main.js'` instead...I think the doc should follow the original file.

**Comment by Tony133** [comment]
@Superoryco, I have updated the configuration with main.js in the old one there is always `server.js`,

if more useful to understand that's fine for me.

if you find something wrong write me.

I commit with the fix.

thanks again for reporting

**Comment by noenif** [comment]
> Let's recap:
> 
> For configuration `webpack-hmr.config.js`:
> 
> ` npm i --save-dev webpack-node-externals start-server-nestjs-webpack-plugin`
> 
> or
> 
> ` npm i --save-dev webpack-node-externals run-script-webpack-plugin webpack`
> 
> for yarn
> 
> `yarn add -D webpack-node-externals run-script-webpack-plugin webpack`
> 
> If you use the yarn 2, instead of installing `webpack-node-externals`, you should install` webpack-pnp-externals`
> 
> Configuration for Yarn 2:
> 
> ```ts
> const webpack = require('webpack');
> const { WebpackPnpExternals } = require('webpack-pnp-externals');
> const { RunScriptWebpackPlugin } = require('run-script-webpack-plugin');
> module.exports = function(options) {
>   return {
>     ...options,
>     entry: ['webpack/hot/poll?100', options.entry],
>     externals: [
>       WebpackPnpExternals({
>         exclude: ['webpack/hot/poll?100'],
>       }),
>     ],
>     plugins: [
>       ...options.plugins,
>       new webpack.HotModuleReplacementPlugin(),
>       new webpack.WatchIgnorePlugin({
>         paths: [/\.js$/, /\.d\.ts$/]
>       }),
>       new RunScriptWebpackPlugin({ name: options.output.filename }),
>     ],
>   };
> };
> ```
> 
> If you are using one of the latest versions of NestJS, webpack 5.x is used, instead of installing `start-server-webpack-plugin`, you should install `start-server-nestjs-webpack-plugin` or `run-script-webpack-plugin webpack`
> 
> Once the installation is complete.
> 
> To create the `webpack-hmr.confi.js` configuration file the configuration is the following:
> 
> ```ts
> const webpack = require('webpack');
> const nodeExternals = require('webpack-node-externals');
> const StartServerPlugin = require('start-server-nestjs-webpack-plugin');
> 
> module.exports = function(options) {
>   return {
>     ...options,
>     entry: ['webpack/hot/poll?100', options.entry],
>     externals: [
>       nodeExternals({
>         allowlist: ['webpack/hot/poll?100'],
>       }),
>     ],
>     plugins: [
>       ...options.plugins,
>       new webpack.HotModuleReplacementPlugin(),
>       new webpack.WatchIgnorePlugin({
>         paths: [/\.js$/, /\.d\.ts$/]
>       }),
>       new StartServerPlugin({ name: options.output.filename }),
>     ],
>   };
> };
> ```
> 
> Add script to your `package.json` file:
> 
> `"start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch"`
> 
> For configuration `webpack.config.js`:
> 
> `npm i --save-dev webpack webpack-cli webpack-node-externals ts-loader run-script-webpack-plugin`
> 
> for yarn
> 
> `yarn add -D webpack webpack-cli webpack-pnp-externals ts-loader run-script-webpack-plugin`
> 
> If you use the yarn 2, instead of installing `webpack-node-externals`, you should install` webpack-pnp-externals`
> 
> Configuration yarn 2:
> 
> ```ts
> const webpack = require('webpack');
> const path = require('path');
> const { WebpackPnpExternals } = require('webpack-pnp-externals');
> const { RunScriptWebpackPlugin } = require('run-script-webpack-plugin');
> module.exports = {
>   entry: ['webpack/hot/poll?100', './src/main.ts'],
>   target: 'node',
>   externals: [
>     WebpackPnpExternals({
>       exclude: ['webpack/hot/poll?100'],
>     }),
>   ],
>   module: {
>     rules: [
>       {
>         test: /.tsx?$/,
>         use: 'ts-loader',
>         exclude: /node_modules/,
>       },
>     ],
>   },
>   mode: 'development',
>   resolve: {
>     extensions: ['.tsx', '.ts', '.js'],
>   },
>   plugins: [
>     new webpack.HotModuleReplacementPlugin(),
>     new RunScriptWebpackPlugin({ name: 'main.js' }),
>   ],
>   output: {
>     path: path.join(__dirname, 'dist'),
>     filename: 'main.js',
>   },
> };
> ```
> 
> To create the `webpack.config.js` configuration file the configuration is the following:
> 
> ```ts
> const webpack = require('webpack');
> const path = require('path');
> const nodeExternals = require('webpack-node-externals');
> const { RunScriptWebpackPlugin } = require('run-script-webpack-plugin');
> 
> module.exports = {
>   entry: ['webpack/hot/poll?100', './src/main.ts'],
>   target: 'node',
>   externals: [
>     nodeExternals({
>       allowlist: ['webpack/hot/poll?100'],
>     }),
>   ],
>   module: {
>     rules: [
>       {
>         test: /.tsx?$/,
>         use: 'ts-loader',
>         exclude: /node_modules/,
>       },
>     ],
>   },
>   mode: 'development',
>   resolve: {
>     extensions: ['.tsx', '.ts', '.js'],
>   },
>   plugins: [
>     new webpack.HotModuleReplacementPlugin(),
>     new RunScriptWebpackPlugin({ name: 'main.js' }),
>   ],
>   output: {
>     path: path.join(__dirname, 'dist'),
>     filename: 'main.js',
>   },
> };
> ```
> 
> Add script to your `package.json` file
> 
> ```
> `"start:dev": "webpack --config webpack.config.js --watch"
> `
> ```
> 
> Hope it helps to understand better while waiting for a reviewers.

使用webpack是正常的,如果使用webpack-hmr.config.js,则是不正常的

**Comment by m4r4c00ch0** [comment]
> For me, using webpack 5.9.0
> 
> 1. remove watch: true in webpack-hmr.config.js
> 2. add --watch to package script: "start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch"
> 
> The latest webpack 5.11.1 webpack will throw "The 'compilation' argument must be an instance of Compilation" Error.

how did you fix the compilation error? I get the same one.

**Comment by Tony133** [comment]
Hi @m4r4c00ch0 which version of webpack do you use?  5.11.1 ?

**Comment by m4r4c00ch0** [comment]
> Hi @m4r4c00ch0, which version of webpack do you use? 5.11.1 ?

@Tony133 latest one `"webpack": "^5.21.2",`

**Comment by Tony133** [comment]
@m4r4c00ch0  If you have time, you can leave a minimal reproduction of a clonable git repository with the problem?

**Comment by Superoryco** [comment]
> > For me, using webpack 5.9.0
> > 
> > 1. remove watch: true in webpack-hmr.config.js
> > 2. add --watch to package script: "start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch"
> > 
> > The latest webpack 5.11.1 webpack will throw "The 'compilation' argument must be an instance of Compilation" Error.
> 
> how did you fix the compilation error? I get the same one.

Well, I'am just using webpack 5.9.0 to avoid the compilation error...

**Comment by Tony133** [comment]
Hi @Superoryco, have you tried doing a fresh install of webpack on a fresh install of Nest typescript starter? gives you the same error?

**Comment by Superoryco** [comment]
> Hi @Superoryco, have you tried doing a fresh install of webpack on a fresh install of Nest typescript starter? gives you the same error?



> Hi @Superoryco, have you tried doing a fresh install of webpack on a fresh install of Nest typescript starter? gives you the same error?

With the latest @nestjs/cli 7.5.5, following the [recap,](https://github.com/nestjs/docs.nestjs.com/pull/1568#issuecomment-752774045) the project will install the latest webpack 5.22.0. And:

if I follow the steps for webpack-hmr.config.js, still get the "The 'compilation' argument must be an instance of Compilation" Error.

but, if I use webpack.config.js, hmr works without any error!

Hopefully, we may finish this issue soon. :joy:

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1621

**Comment by Tony133** [comment]
@kamilmysliwiec this pull compared to the one that should replace this, respects the guidelines of the documentation while that does not. Should we close this?

**Comment by mlightvn** [comment]
@Tony133 
Thank you, your comment works for me.
https://github.com/nestjs/docs.nestjs.com/pull/1568#issuecomment-740773276

**Pull request closed without merging**
