### PR TITLE
docs(integrations): Linking the NestJS Yoga integration to GraphQL docs

### PR DESCRIPTION
**Pull request by Urigo**
Pointing to the Yoga integration next to the other integrations.

Just in time after it was updated to the latest NestJS 9 and Yoga v3! 
https://the-guild.dev/blog/graphql-yoga-nestjs-v9

### CODE REVIEW

**Comment by Urigo** [comment]
hi @kamilmysliwiec, any chance you can have a short look on this?
thanks

**Review by jmcdo29 — APPROVED** [review]
LGTM.

Thank you for mentioning that this is not from Nest directly. Hopefully that keeps us from getting issues for your integration

**Review by micalevisk — APPROVED** [review]
@kamilmysliwiec can we merge this?

**Comment by kamilmysliwiec** [comment]
I've been going through tons of PRs today and will check this one out shortly too. It won't get merged in the current state/version though, we need to distinguish between official packages/3rd-party libraries. I'll fix it up soon

**Comment by Urigo** [comment]
@kamilmysliwiec I specifically wrote that as a separate part of the Apollo and Mercurius integration and wrote that it is @the-guild-org that supports that integration. 
I'm happy to change the wording to anything you want, just let me know how, otherwise I can't know what to do

**Comment by Urigo** [comment]
also I think there are a couple of things worth taking from https://github.com/nestjs/docs.nestjs.com/pull/2398/ but it'a hard when we are not getting feedback.

**Comment by Urigo** [comment]
also, if you need to jump to a call or anything else we at @the-guild-org can help with this repo, including reviewing more PRs and becoming more active and supporting maintainers (we are doing a lot of NestJS development and have a lot of knowledge and time to invest), please let us know! ❤️

**Pull request merged**
