### PR TITLE
feat: enable Angular Universal

### PR DESCRIPTION
**Pull request by beeman**
@markpieszak could you take a look please?

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
great job Bram, made during the workshop huh 🙂 ? will pull, thanks man 💪

**Comment by beeman** [comment]
Thanks @kamilmysliwiec - Indeed, made during the workshop. Let me know if you need any input/help with it :-)

**Comment by CWSpear** [comment]
There are some changes that could be made to bring this up to date with Angular 6. `.angular-cli.json` -> `angular.json` and the structure is a bit different, IIRC.

**Comment by johannesschobel** [comment]
@beeman what is the current state of this PR? does this need any further improvements and clarification for newer angular versions?

**Comment by kamilmysliwiec** [comment]
Every page is now prerendered thanks to netlify :)

**Pull request closed without merging**
