### PR TITLE
content: introduction and first steps page edits

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[X] Other... Please describe:
```
This is a documentation only PR.

Hi, sorry for the longish PR description.

I'm volunteering to do some light-to-medium edits of the Nest docs.  By that I mean:
* cleaning up typo's (there are very few!) and other minor fixes (e.g., a few hyperlinks use http instead of https, and other similar corrections)
* some relatively minor rewording to provide greater clarity
* some grammar and style changes to make the docs read more naturally to native English speakers

If someone is already performing this role, I'm glad to offer my assistance, but am also willing to lead the way if there is nobody currently in that role, at least for now.

On the "medium edits" end of the scale, I've also submitted some "improvements" that don't really go to the core of how the platform works or address best practices, but try to flesh out an existing well understood concept with a bit more detail to ease new user onboarding.  

In the future, I'm willing to work on creating new or more substantial improvements to the documentation as well, though I'd like to have some feedback on the initial changes first, while I also gain more experience with Nest.

In this PR, I'm submitting the Introduction and First Steps pages to provide a small but meaningful sample to get feedback before continuing. I'm hoping this encourages a few of the core team members to take a look and give feedback!

I'm very impressed with the Nest platform and community, and I'm excited to participate in this small way in improving Nest, and look forward to feedback from the community.

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Wow. I love this PR! Thank you for your contribution, I'll surely review it shortly. 

> If someone is already performing this role, I'm glad to offer my assistance, but am also willing to lead the way if there is nobody currently in that role, at least for now.

That would be amazing. 99% of docs are written by me so far (and I'm not a native speaker so there may be some grammatical issues for sure ;))

Looking forward to more PRs!

**Comment by johnbiundo** [comment]
Well, your English is far better than a lot of native speakers I know :-).  And the docs are really quite good.  I'm glad to contribute any way I can, as I've quickly become a big fan of Nest.

I want to find the right balance between actively trying to improve, but not overstep my bounds (or relatively limited depth at this juncture).  I also aim to put as little burden on you to review as possible.

Feel free to offer whatever feedback you have time for.  And I'm never insulted by feedback, so don't worry about hurting my feelings :-)

**Comment by kamilmysliwiec** [comment]
Thank you @johnbiundo :) In the meantime, could you please remove auto-generated HTML files?  I have just excluded them from repository (to avoid conflicts and messy PRs - only markdown is important now)

**Comment by johnbiundo** [comment]
@kamilmysliwiec  I have just pushed a commit that deletes the HTML files.  

I'm not sure why they were generated, since I ran only the watch task, not the build task.  I'm probably missing something in the workflow (haven't used a markdown generation workflow before), but in ancy case I'll make sure they're not present in future commits.  Thanks!

**Comment by BrunnerLivio** [comment]
Really cool, great job @johnbiundo! 
@kamilmysliwiec just did a recent push on master which deletes the HTML files as proposed in #288.
You need to rebase with upstream/master so the generated HTML files won't bother you anymore. Do you need assistance with that?

**Comment by johnbiundo** [comment]
Thanks @BrunnerLivio .  I think I've got it, but just to be sure, do I just
git fetch upstream
git rebase upstream/master

**Comment by BrunnerLivio** [comment]
@johnbiundo if you have setup the upstream remote to point to this repository, then this should work perfectly fine :)

**Comment by johnbiundo** [comment]
Welp, I appear to have pooched my local repo :-(   

I'm not sure what happened, but the rebase failed.

Sorry, I'm a little out of my depth with git on this one.  I want to make this as easy as possible on you guys, so let me know what you suggest.  I can see on Github that my remote branch on my fork is still there, and I can easily recover the changes from there.  

I don't mind fumbling around on my end to get it right, but don't want to mess you up.  Is it acceptable to delete the pull request, re-clone from master, re-apply the changes, and submit a new PR?  I'm sure there's probably a better way, but I'd rather not use up more of you guys' time to walk me through git surgery.

**Comment by johnbiundo** [comment]
@BrunnerLivio I think what may have happened is when @kamilmysliwiec asked me to remove the HTML files, I deleted them and pushed a new commit to the remote for this PR.  Here's what my git status looks like:

image


Should I just be able to do a git rm on those unmerged files, then commit the modified md files?

**Comment by BrunnerLivio** [comment]
@johnbiundo fixed it for short and created a PR on your fork :) I used

```sh
git fetch --all
git rebase upstream/master
git rm "the/files.html"
git rebase --continue
git push origin master --force
```

**Comment by kamilmysliwiec** [comment]
No worries @johnbiundo, everything works well :) Thanks again!

**Comment by johnbiundo** [comment]
Thanks so much guys!  I appreciate it.  I'll get started on some additional edits shortly!

**Pull request merged**
