### PR TITLE
Feature/add discord icon

### PR DESCRIPTION
**Pull request by BrunnerLivio**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?
No discord badge in the header

## What is the new behavior?
- Upgrade font-awesome to 5.8.1 (Discord badge was introduced in 5.x)

- New discord badge in the header
Selection_029

- Add missing stackoverflow + Discord badge in the footer
Selection_030

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
For some reason, I can't see the last icon:
image

**Comment by kamilmysliwiec** [comment]
Arrows seem to be broken as well
image

**Comment by BrunnerLivio** [comment]
Hmm I checked those icons before submitting the PR. Probably had the old icons cached or so. Will fix!

**Comment by BrunnerLivio** [comment]
Fixed!

**Comment by kamilmysliwiec** [comment]
Thank you @BrunnerLivio 💥 

Is there a thin version of an arrow icon? This one seems to be "heavy". 
Now:
image

Before:
image

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec Unfortunately [light/regular icons](https://fontawesome.com/icons/chevron-up?style=light) are now part of the FontAwesome pro pack. Therefore I have used the `solid` style.

**Comment by kamilmysliwiec** [comment]
😢 maybe we should just use an SVG image for discord? I'm sorry about your great work here so far!

**Pull request closed without merging**
