### PR TITLE
doc(controllers.md) - edits for clarity on @Res, @Response; mention response handling for primitive types

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Documentation

## Other information

@kamilmysliwiec Controllers chapter edits for clarity.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Actually, both `@Res()` and `@Response()` will give you the same value. We provided an alias (`@Res()`) to avoid conflicts with express/fastify typings.

**Comment by johnbiundo** [comment]
Ah, so I could simplify this significantly merely by explaining that.  Let me try to do so.  Will take me until at least the weekend as I'm on jury duty right now :(

**Comment by johnbiundo** [comment]
Updated to reflect @kamilmysliwiec comment.

**Comment by kamilmysliwiec** [comment]
Thanks @johnbiundo! Can you please resolve conflicts :)?

**Comment by johnbiundo** [comment]
@kamilmysliwiec conflicts fixed.  The build checks are failing; I've let @BrunnerLivio know.

**Comment by kamilmysliwiec** [comment]
Let me look at them real quick

**Pull request merged**
