### PR TITLE
docs(who-uses): add hinge health

### PR DESCRIPTION
**Pull request by sahellebusch**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
Adding a new sponsor to the list.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?
Not in the list.

## What is the new behavior?
My company is in the list.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sahellebusch** [comment]
Shows up locally
image

**Comment by jmcdo29** [comment]
We're working on not adding so many logos to the who uses page to speed up the loading of the page. You're more than welcome to add your name the list though, just without the logo please and thank you.

**Comment by sahellebusch** [comment]
Oh, that's a bummer. Maybe a sponsors page at some point then. I'll remove.

**Comment by kamilmysliwiec** [comment]
I think we can make a one-time exception in this case - Hinge health is quite a large, well-known company. I'd be more than happy to see their logo in the docs 🙌

**Pull request merged**
