### PR TITLE
docs(performance): add file name

### PR DESCRIPTION
**Pull request by Zerotask**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?
no file name provided

Issue Number: N/A

## What is the new behavior?
file name added

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Zerotask** [comment]
Netlify build is failing with: `ERR! cb() never called!`
This is not related to my changes.

**Comment by micalevisk** [comment]
I believe they didn't added the file name in that snippet on purpose because it's not a full valid code _(as the first one is)_, it just shows a minor change that you'll need to make.

**Comment by Zerotask** [comment]
> it just shows a minor change that you'll need to make.

And in which wile?

It doesn't add much noise to the documentation to clearify that the main.ts file is meant. 
If a snippet would be suitable for different files, then yes, it could be omitted

**Comment by micalevisk** [comment]
> And in which file?

I believe this clear if you have read from top to bottom. Also the snippet is pretty unique (because it has `bootstrap` etc)

---

When I saw file names on code snippets I assume that I can just copy the snippet, create a file with that name and paste it. Maybe using `// on main.ts file` is better

**Comment by Zerotask** [comment]
> When I saw file names on code snippets I assume that I can just copy the snippet

If you read the documentation from top to down, you wouldn't assume this.

In my opinion it's a bad UX to randomly drop the file name from code snippets. But it's not my decision for this project. If you have a different opinion, just close my PR.

**Comment by micalevisk** [comment]
> you wouldn't assume this.

maybe in another case but for this one, we can as they are pretty close to each other. See:

image

> just close my PR.

I'm just a contributor just like you xD

---

> In my opinion it's a bad UX to randomly drop the file name from code snippets

You can think like this:

- when the snippet have a file name, then it means you can copy it to create a working code
- when it doesn't, it is just a snippet to show off something minimal

image

then the UX will be fine, I guess.

**Comment by Zerotask** [comment]
> when it doesn't, it is just a snippet to show off something minimal

That is not true. There are and there was (before I added some) complete files without file names.
That is just your view.

A file name just give you the extra information where this snippet should be placed in. A developer should never copy and paste something without knowing what it does.

But I don't want to start a discussion here. You have pointed out your view, I did mine.

**Pull request closed without merging**
