### PR TITLE
fix(mapped-types.md): Functions import error

### PR DESCRIPTION
**Pull request by OmarHassouna-PS**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

In the 'HINT' sections there is an error in the name of the package from which the Functions must be imported. They must be from @nestjs/mapped-types

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jmcdo29** [comment]
This is not an error. This section is dedicated to the use of the NestJS _swagger_ mapped types, which do exist. They build on top of the `@nestjs/mapped-types` package, just like `@nestjs/graphql`'s mapped-types do

**Comment by OmarHassouna-PS** [comment]
> This is not an error. This section is dedicated to the use of the NestJS _swagger_ mapped types, which do exist. They build on top of the `@nestjs/mapped-types` package, just like `@nestjs/graphql`'s mapped-types do

image


Yes, I am aware of that, but the function must be prepared from '@nestjs/mapped-types', Even if we were in the NestJS swagger mapped types section, 

It seems I made a mistake in describing them as categories, I mean functions like PartialType() function

**Comment by jmcdo29** [comment]
Again, [`@nestjs/swagger` has all of these `PartialType`, `OmitType`, etc functions available for use](https://github.com/nestjs/swagger/tree/master/lib/type-helpers). They build on top of `@nestjs/mapped-types`, but include the swagger metadata as well, and as this is the swagger portion of the docs, it stands to reason that the `@nestjs/swagger` package is the correct one to reference here

**Comment by OmarHassouna-PS** [comment]
> Again, [`@nestjs/swagger` has all of these `PartialType`, `OmitType`, etc functions available for use](https://github.com/nestjs/swagger/tree/master/lib/type-helpers). They build on top of `@nestjs/mapped-types`, but include the swagger metadata as well, and as this is the swagger portion of the docs, it stands to reason that the `@nestjs/swagger` package is the correct one to reference here

Ok, I got you now thanks for explaining, Should I close Commit?

**Comment by jmcdo29** [comment]
Yes, the docs are correct and the PR isn't necessary. Thanks for your contribution though!

**Comment by OmarHassouna-PS** [comment]
> Yes, the docs are correct and the PR isn't necessary. Thanks for your contribution though!

My pleasure

**Pull request closed without merging**
