### PR TITLE
docs: fastify inside docker 

### PR DESCRIPTION
**Pull request by dribro**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Other... Please describe: Documentation
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/docs.nestjs.com/issues/145

## What is the new behavior?
new notice and a small code snippet

image

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Some white-space and due to lint enforcing and stuff like that, but nothing was broken nor anything like that.

I assumed it wasn't problematic, so here it is.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Not sure if we should put sample code immediately after `blockquote` tag (and refer to it inside quote). Maybe, let's extract this tip outside of the `blockquote` (just use a simple paragraph)

**Comment by dribro** [comment]
You're saying the content of the notice should be a normal paragraph?

**Comment by kamilmysliwiec** [comment]
That's how I think 😅 do you think it's fine?

**Comment by dribro** [comment]
image
what do ya think?

**Comment by kamilmysliwiec** [comment]
Looks cool 👍

**Comment by dribro** [comment]
ready to go.
Thanks for the patience, this was a first for me

**Comment by kamilmysliwiec** [comment]
Thanks @dribro 👍

**Pull request merged**
