### PR TITLE
docs(devtools/ci-cd): change 'Github' to 'GitHub'

### PR DESCRIPTION
**Pull request by itecompro**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

It hasn't been mentioned explicitly in [GitHub Logs and Usage](https://github.com/logos), but based on _"Do not use the **GitHub** name..."_, and all the references of their legal name in [Wikipedia/GitHub](https://en.wikipedia.org/wiki/GitHub), it's actually `GitHub` as opposed to `Github`.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
lgtm

**Comment by Jorge380-cp** [comment]
#1310

**Comment by Jorge380-cp** [comment]
#2882

**Comment by Jorge380-cp** [comment]
#2871

**Pull request merged**
