### PR TITLE
chore(): migration to eslint

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Migration to eslint, with the removal of tslint and codelyzer, as they are deprecated with the new of Angular.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
During the migration from `tslint` to `eslint` there are some different `rules` and changed I put you below:

- 6 ESLint rules ⚠️ behave differently from their TSLint counterparts:
  * arrow-body-style:
    - ESLint will throw an error if the function body is multiline yet has a one-line return on it.
  * @typescript-eslint/no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * no-console:
    - Custom console methods, if they exist, will no longer be allowed.
  * brace-style:
    - ESLint's brace-style will check all tokens.
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
  * no-underscore-dangle:
    - Leading or trailing underscores (_) on identifiers will now be forbidden.

- 5 rules ⚠️ are not known by tslint-to-eslint-config to have ESLint equivalents:
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "import-spacing".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "invoke-injectable".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-access-missing-member".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "templates-use-public".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "whitespace".

the `@typescript-eslint/eslint-plugin-tslint` package, removed it after converting to `eslint`, as it required `tslint`. So I think these last 5 roles are not a problem, to be evaluated however the 6 eslint roles (the ones above).

### CODE REVIEW

**Comment by Tony133** [comment]
I think the time has come to migrate from tslint to eslint, also considering that with the new version of Angular 12.x ❤️ it is no longer integrated during the creation of a new angular project (see [here](https://github.com/angular/angular-cli/pull/20291))

I always fail only the test, which in any case does not concern the changes I have made, however to be evaluated 😄🤞

P.s. NestJS ❤️ 🙌

**Comment by Tony133** [comment]
Hi 👋,

I have updated this PR with the new version of the angular 14.x compatible `@angular-eslint` package and have also aligned the branch with all the new changes that are in the main branch.

The CI has passed ✅ 🙌

If we want to migrate to eslint this can be a solution.

**Comment by kamilmysliwiec** [comment]
Could you resolve conflicts 🙏 ?

**Comment by Tony133** [comment]
I resolved the conflicts and updated the `@angular-eslint/eslint-plugin` package to `v15.1.0` ✅

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
