### PR TITLE
fix(): remove smooth scroll

### PR DESCRIPTION
**Pull request by yannbertrand**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Searching something in the docs using browser search is really inconvenient as the user has to wait a few seconds for the page to scroll.

Kapture 2020-01-07 at 16 30 48

## What is the new behavior?

Directly scroll when typing

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by lazarljubenovic** [comment]
To be honest I was weighing if I should report this is a bug in Chrome or here, and never got around to do either, so forgot about it. Now seeing that it's confusing for other people as well, maybe it means that it's indeed Chrome's fault for doing this. 

I'm wondering if it should be reported to webkit or Chrome, though? 🤔

**Comment by yannbertrand** [comment]
I didn't think about it but it does make sense!

If you want to get a normal scroll behavior on Nest's docs until then you can use:
```js
document.documentElement.style.setProperty('scroll-behavior', 'auto')
```

**Comment by BrunnerLivio** [comment]
Its a [chrome bug](https://support.google.com/chrome/thread/23003371).
I think temporarily setting `auto` scroll behavior as @yannbertrand mentioned is the best option for now.

[Dan Abramov confirmed it too on Twitter](https://twitter.com/dan_abramov/status/1214605699625504770?s=21)

**Comment by kamilmysliwiec** [comment]
Let's close this then

**Comment by yannbertrand** [comment]
I would have preferred this temporary fix integrated until it's solved on Chrome's side. As you can see on the gif from the original post, it's really annoying for Chrome users, and we have no idea on when they will resolve this.

**Pull request closed without merging**
